Simspace/monorail

- packages/components/package.json
- packages/storybook/package.json
- packages/storybook/src/patterns/Toolbar.stories.tsx
- packages/themes/package.json
- packages/themes/src/pcte/components/Avatar/themeOverrides.ts
- packages/themes/src/pcte/theme/dark.tsx
- packages/themes/src/pcte/theme/light.tsx
- packages/themes/src/pcte/theme/themeComponents.ts
- packages/types/package.json
- packages/utils/package.json
🎫 https://resolvn.atlassian.net/browse/UXE-46
🎫 https://resolvn.atlassian.net/browse/UXE-13
Legacy theme but with purple accent colors instead of dark blue.
> [UXE-46][UXE-13] PCTE theme: sizing and color palette

- packages/components/package.json
- packages/components/src/DataGrid/components/DataGridFooter.tsx
- packages/storybook/src/DataGrid/DataGrid.stories.tsx
- packages/themes/package.json
- packages/types/package.json
- packages/utils/package.json
https://simspace.slack.com/archives/CCCBEN3AL/p1688653663848679
Works with quick filter (search input) and a combination of quick filter and column filter(s).
> [NO TICKET] fix: filtered DataGrid pagination count

- packages/components/package.json
- packages/components/src/DataGrid/components/DataGridToolbar.tsx
- packages/themes/package.json
- packages/themes/src/legacy/components/DataGrid/themeOverrides.tsx
- packages/types/package.json
- packages/utils/package.json
https://simspace.slack.com/archives/CCCBEN3AL/p1689049573825629
> fix: DataGridToolbar height and Select alignment

- packages/storybook/src/Chip/Chip.stories.tsx
- packages/storybook/src/Chip/ChipShowcase.stories.tsx
- packages/storybook/src/helpers/storybook.ts
- packages/themes/src/legacy/components/DataGrid/themeOverrides.tsx
- packages/themes/src/meteor/components/Chip/themeOverrides.ts
- packages/themes/src/meteor/theme/dark.ts
- packages/themes/src/meteor/theme/light.ts
- packages/types/src/themeAugmentation.ts
🎫 https://resolvn.atlassian.net/browse/UXE-66
> [UXE-66] DataGrid action IconButton size and fix Meteor Chip in dark mode

- packages/components/src/Autocomplete/Autocomplete.tsx
- packages/components/src/InputBase/InputBase.tsx
- packages/components/src/TextField/TextField.tsx
- packages/storybook/src/Autocomplete/Autocomplete.stories.tsx
- packages/storybook/src/Search/Search.stories.tsx
- packages/storybook/src/Select/Select.stories.tsx
- packages/storybook/src/TextField/TextField.stories.tsx
- packages/themes/src/classic/components/Autocomplete/themeOverrides.tsx
- packages/themes/src/classic/components/Backdrop/themeOverrides.ts
- packages/themes/src/classic/components/Chip/themeOverrides.ts
- packages/themes/src/legacy/components/Autocomplete/themeOverrides.tsx
- packages/themes/src/meteor/components/Autocomplete/themeOverrides.tsx
- packages/themes/src/meteor/components/FormHelperText/themeOverrides.ts
- packages/themes/src/meteor/components/InputBase/themeOverrides.ts
- packages/themes/src/meteor/components/InputLabel/themeOverrides.ts
- packages/themes/src/meteor/components/OutlinedInput/themeOverrides.ts
- packages/themes/src/meteor/theme/themeComponents.ts
🎫 https://resolvn.atlassian.net/browse/UXE-36
Meteor theme component updates:
1. TextField
2. Select
3. Search
4. Autocomplete
> [UXE-36] Meteor Input Fields

- packages/components/package.json
- packages/storybook/src/Button/Button.stories.tsx
- packages/storybook/src/IconButton/IconButton.stories.tsx
- packages/storybook/src/ToggleButton/ToggleButton.stories.tsx
- packages/themes/package.json
- packages/themes/src/meteor/components/Button/themeOverrides.ts
- packages/themes/src/meteor/components/IconButton/themeOverrides.ts
- packages/themes/src/meteor/components/ToggleButton/themeOverrides.ts
- packages/themes/src/meteor/theme/baseTheme.ts
- packages/themes/src/meteor/theme/themeComponents.ts
- packages/types/package.json
- packages/utils/package.json
🎫 https://resolvn.atlassian.net/browse/UXE-68
Meteor theme component updates:
1. Button
2. IconButton
3. SplitButton
4. ToggleButton
5. ToggleButtonGroup
> [UXE-68] Meteor Button updates

- packages/themes/src/meteor/components/FormLabel/themeOverrides.ts
- packages/themes/src/meteor/components/InputLabel/themeOverrides.ts
- packages/themes/src/meteor/components/Switch/themeOverrides.ts
- packages/themes/src/meteor/theme/themeComponents.ts
🎫 https://resolvn.atlassian.net/browse/UXE-69
Meteor theme component updates:
1. Checkbox
2. Radio
3. Switch
> [UXE-69] Meteor Inputs: Checkbox, Radio, Switch

- packages/components/package.json
- packages/components/src/Link/Link.tsx
- packages/themes/package.json
- packages/types/package.json
- packages/utils/package.json
🎫 https://resolvn.atlassian.net/browse/UXE-109
> [UXE-109] Fix Link type support `component` prop

- packages/themes/src/meteor/theme/baseTheme.ts
🎫 https://resolvn.atlassian.net/browse/UXE-49
- Set `font-weight: 400` for `MenuItem` and `MenuItemDense`
> [UXE-49] Meteor - Update MenuItem Typography Style

- packages/components/src/IconChip/IconChip.tsx
🎫 https://resolvn.atlassian.net/browse/UXE-74
> [UXE-74] Meteor IconChip sizes

- packages/components/package.json
- packages/components/src/ResizeHandle/ResizeHandle.tsx
- packages/themes/package.json
- packages/types/package.json
- packages/utils/package.json
🎫 https://resolvn.atlassian.net/browse/UXE-67
> [UXE-67] ResizeHandle handle texture and updated colors

- packages/components/src/Divider/Divider.tsx
- packages/components/src/themeAugmentation.ts
- packages/storybook/src/Divider/Divider.stories.tsx
- packages/themes/src/classic/components/Divider/themeOverrides.ts
- packages/themes/src/classic/theme/themeComponents.ts
- packages/themes/src/legacy/components/Divider/themeOverrides.ts
🎫 https://resolvn.atlassian.net/browse/UXE-125
> [UXE-125] Divider spacing prop

- packages/themes/src/meteor/theme/light.ts
🎫 https://resolvn.atlassian.net/browse/UXE-133
> [UXE-133] Update Meteor light grey ramp

- packages/components/package.json
- packages/storybook/src/TreeItem/TreeItem.stories.tsx
- packages/storybook/src/TreeView/TreeView.stories.tsx
- packages/themes/package.json
- packages/themes/src/meteor/components/TreeItem/themeOverrides.ts
- packages/themes/src/meteor/theme/themeComponents.ts
- packages/types/package.json
- packages/utils/package.json
🎫 https://resolvn.atlassian.net/browse/UXE-130
> [UXE-130] Modify TreeItem

- packages/themes/src/meteor/components/PaginationItem/themeOverrides.ts
🎫 https://resolvn.atlassian.net/browse/UXE-61
> [UXE-61] Meteor: PaginationItem text color

- packages/components/package.json
- packages/themes/package.json
- packages/themes/src/meteor/theme/dark.ts
- packages/types/package.json
- packages/utils/package.json
🎫 https://resolvn.atlassian.net/browse/UXE-137
> [UXE-137] Update Meteor dark mode backdropOverlay token

- packages/components/package.json
- packages/themes/package.json
- packages/themes/src/meteor/theme/dark.ts
- packages/themes/src/meteor/theme/light.ts
- packages/types/package.json
- packages/types/src/themeAugmentation.ts
- packages/utils/package.json
🎫 [UXE-139] https://resolvn.atlassian.net/browse/UXE-139
[UXE-139]: https://resolvn.atlassian.net/browse/UXE-139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(meteor theme): add app icon and illustration color tokens

- packages/components/package.json
- packages/components/src/DataGrid/components/DataGridFooter.tsx
- packages/themes/package.json
- packages/types/package.json
- packages/utils/package.json
When server-paginated, the total row count of DataGrid would not update consistently. This PR fixes the issue.
> [No Ticket] fix(data-grid): total row count

- packages/components/package.json
- packages/components/src/LinearProgress/LinearProgress.tsx
- packages/storybook/src/LinearProgress/LinearProgress.stories.tsx
- packages/themes/package.json
- packages/themes/src/classic/components/LinearProgress/themeOverrides.ts
- packages/themes/src/meteor/components/LinearProgress/themeOverrides.ts
- packages/types/package.json
- packages/utils/package.json
🎫 https://resolvn.atlassian.net/browse/UXE-155
> [UXE-155] Add Percent to Linear Progress Indeterminate

- packages/components/package.json
- packages/components/src/IconButton/IconButton.tsx
- packages/components/src/PasswordTextField/PasswordTextField.tsx
- packages/components/src/Search/Search.tsx
- packages/storybook/src/IconButton/IconButton.stories.tsx
- packages/themes/package.json
- packages/themes/src/classic/components/IconButton/themeOverrides.ts
- packages/themes/src/legacy/components/IconButton/themeOverrides.ts
- packages/themes/src/meteor/components/Autocomplete/themeOverrides.tsx
- packages/themes/src/meteor/components/Button/themeOverrides.ts
- packages/themes/src/meteor/components/IconButton/themeOverrides.ts
- packages/themes/src/meteor/theme/dark.ts
- packages/themes/src/meteor/theme/light.ts
- packages/types/package.json
- packages/utils/package.json
[CFP-2713](https://resolvn.atlassian.net/browse/CFP-2713)
This PR updates the meteor styling for Icon Buttons to reflect the [newest designs](https://www.figma.com/file/AF2iysvnM1NMDx7oCS93A3/%E2%9A%99%EF%B8%8F-Monorail?type=design&node-id=6557%3A38486&mode=dev)
[CFP-2713]: https://resolvn.atlassian.net/browse/CFP-2713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CFP-2713] feat: update meteor icon button styles

- packages/components/package.json
- packages/components/src/Chip/Chip.tsx
- packages/storybook/src/Chip/Chip.stories.tsx
- packages/storybook/src/Chip/ChipShowcase.stories.tsx
- packages/themes/package.json
- packages/themes/src/meteor/components/Chip/themeOverrides.ts
- packages/types/package.json
- packages/utils/package.json
[CFP-2755](https://resolvn.atlassian.net/browse/CFP-2755)
[Figma - Monorail Chip](https://www.figma.com/design/AF2iysvnM1NMDx7oCS93A3/%E2%9A%99%EF%B8%8F-Monorail?node-id=19469-42719&m=dev)
This PR updates the Meteor theme styling for Chip.
[CFP-2755]: https://resolvn.atlassian.net/browse/CFP-2755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: meteor chip style updates

- packages/components/package.json
- packages/components/src/ResizableHandle/ResizableHandle.tsx
- packages/components/src/ResizableHandle/resizableHandleProps.ts
- packages/themes/package.json
- packages/types/package.json
- packages/utils/package.json
Removes margin around `ResizableHandle`
> [CFP-2678] fix(resizable-handle): no margin around handle

- packages/components/package.json
- packages/components/src/ResizableDrawer/ResizableDrawer.tsx
- packages/storybook/src/Drawer/Drawer.stories.tsx
- packages/themes/package.json
- packages/types/package.json
- packages/utils/package.json
[CFP-2850](https://resolvn.atlassian.net/browse/CFP-2850)
This PR corrects the logic for calculating the width of the resizable drawer when a user interacts with the drawers handle.
[CFP-2850]: https://resolvn.atlassian.net/browse/CFP-2850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [CFP-2850] fix: width of resizable drawer logic

- packages/components/package.json
- packages/components/src/ResizableElement/ResizableElement.tsx
- packages/storybook/src/ResizableContainer/ResizableContainer.stories.tsx
- packages/themes/package.json
- packages/types/package.json
- packages/utils/package.json
`defaultSize` must be computed before the component mounts for the first time
> fix(resizable-container): defaultSize

- packages/components/package.json
- packages/components/src/Search/Search.tsx
- packages/themes/package.json
- packages/types/package.json
- packages/utils/package.json
- [Jira](https://resolvn.atlassian.net/browse/CFP-3019)
> [CFP-3019] Fixed clear button alignment on search input

- packages/components/package.json
- packages/components/src/DataGrid/components/DataGridCell.tsx
- packages/components/src/DataGrid/constants/dataGridClasses.ts
- packages/themes/package.json
- packages/themes/src/classic/components/DataGrid/themeOverrides.tsx
- packages/themes/src/legacy/components/DataGrid/themeOverrides.tsx
- packages/themes/src/meteor/components/DataGrid/themeOverrides.tsx
- packages/types/package.json
- packages/utils/package.json
Fixes fullWidth cells after `@mui/x-data-grid` v7 upgrade.
> fix: data grid fullWith cell

- packages/components/package.json
- packages/components/src/DateTimePicker/DateTimePicker.tsx
- packages/themes/package.json
- packages/themes/src/classic/components/PickersLayout/themeOverrides.ts
- packages/types/package.json
- packages/utils/package.json
- Border radius for time buttons
- Background color for days when it's focus
Legacy theme
Meteor theme
> [PRTL-4190] Date time picker update

- packages/components/package.json
- packages/themes/package.json
- packages/themes/src/meteor/components/Button/themeOverrides.ts
- packages/themes/src/meteor/components/SvgIcon/themeOverrides.ts
- packages/themes/src/meteor/theme/themeComponents.ts
- packages/types/package.json
- packages/utils/package.json
The icon size for the meteor theme was slightly bigger than what we have on the designs
> [NG-1618] Icon fixes

- packages/components/package.json
- packages/components/src/FileUpload/FileUpload.tsx
- packages/components/src/FileUpload/fileUploadProps.ts
- packages/themes/package.json
- packages/types/package.json
- packages/utils/package.json
Add accept prop to Upload file component
> [PRTL-4573] Upload file multiple
