dist/package.json, dist/pageComponents/errorPage/ErrorPage.js, dist/visualComponents/inputs/TextArea.d.ts, dist/visualComponents/inputs/TextArea.js, package.json, src/pageComponents/errorPage/ErrorPage.tsx, src/visualComponents/inputs/TextArea.tsx
**Monorail Release v0.0.21  - Amrheins**
`src/pageComponents/errorPage/ErrorPage.tsx`
*   Add `color` CSS to manually override colors being inherited from Bootstrap
`src/visualComponents/inputs/TextArea.tsx`
*   Add `onKeyDown` prop to recognize keystroke actions in the `TextArea`. E.g. `key === enter` to `submit()`
=> Monorail Release v0.0.21  - 'Amrheins'

packages/components/package.json, packages/themes/package.json, packages/themes/src/meteor/components/ListItemAvatar/themeOverrides.ts, packages/types/package.json, packages/utils/package.json
Component: `ListItemAvatar`
Theme: Meteor
Removes fixed width and height to adapt to the child `Avatar`'s size.
=> fix: list item avatar dimensions

packages/components/src/IconButton/IconButton.tsx, packages/storybook/src/IconButton/IconButton.stories.tsx, packages/storybook/src/theme/palette/SemanticColors.stories.tsx, packages/themes/src/classic/theme/dark.ts, packages/themes/src/classic/theme/light.ts, packages/themes/src/legacy/theme/dark.ts, packages/themes/src/legacy/theme/light.ts, packages/themes/src/meteor/theme/dark.ts, packages/themes/src/meteor/theme/light.ts, packages/themes/src/pcte/theme/dark.tsx, packages/themes/src/pcte/theme/light.tsx, packages/types/src/themeAugmentation.ts
🎫 https://resolvn.atlassian.net/browse/UXE-80
- Added `secondary.lowEmphasis`, `.border`, `.focusRing`, `hover`, and `active` color tokens to all themes.
- Re-enabled the `<IconButton color="secondary" />` variant.
=> [UXE-80] IconButton: Re-enable secondary color variant

packages/components/package.json, packages/components/src/Link/Link.tsx, packages/components/src/ListItemText/ListItemText.tsx, packages/components/src/Typography/Typography.tsx, packages/storybook/src/Link/Link.stories.tsx, packages/themes/package.json, packages/types/package.json, packages/utils/package.json, packages/utils/src/helpers.ts, packages/utils/src/helpers/getLineClampStyles.ts, packages/utils/src/hooks.ts
🎫 https://resolvn.atlassian.net/browse/UXE-104
`@monorail/components`
- Adds `lineClamp` prop support for the Link component
`@monorail/utils`
- Exports `getLineClampStyles` as a reusable helper
- Exports `useMediaQuery` from MUI
=> [UXE-104] Add lineClamp prop to Link

packages/components/package.json, packages/storybook/src/ListSubheader/ListSubheader.stories.tsx, packages/themes/package.json, packages/themes/src/classic/components/ListSubheader/themeOverrides.ts, packages/themes/src/legacy/components/ListSubheader/themeOverrides.tsx, packages/types/package.json, packages/utils/package.json
🎫 https://resolvn.atlassian.net/browse/UXE-124
- Modified `ListSubheader` styles to push additional elements to the right by default.
- Added story: ListSubheader/With Action Buttons
- Added story: ListSubheader/Text Overflow
=> [UXE-124] ListSubheader action buttons

packages/components/package.json, packages/components/src/DataGrid/components/DataGridFooter.tsx, packages/components/src/DataGrid/hooks/useDataGridProps.ts, packages/storybook/src/DataGrid/DataGridPagination.stories.tsx, packages/themes/package.json, packages/types/package.json, packages/utils/package.json, packages/utils/src/hooks.ts, packages/utils/src/hooks/useLatch.ts
I used DataGrid to implement a server-paginated table and noticed that it wasn't working. It only showed one page, even though I was passing in the `rowCount` prop, which provides the total number of rows that the server could send. Upon further investigation, I noticed it was because of an issue in the implementation of our pagination footer in Monorail.
This PR fixes the implementation, as well as corrects some inconsistencies in the display of the row range in the right corner of the pagination footer.
=> fix(data-grid): server pagination

packages/components/package.json, packages/storybook/src/theme/palette/Foundation.stories.tsx, packages/themes/package.json, packages/themes/src/classic/components/Autocomplete/themeOverrides.tsx, packages/themes/src/classic/components/InputBase/themeOverrides.ts, packages/themes/src/classic/theme/dark.ts, packages/themes/src/classic/theme/light.ts, packages/themes/src/legacy/components/InputBase/themeOverrides.ts, packages/themes/src/legacy/theme/dark.ts, packages/themes/src/legacy/theme/light.ts, packages/themes/src/meteor/components/Autocomplete/themeOverrides.tsx, packages/themes/src/meteor/components/InputBase/themeOverrides.ts, packages/themes/src/meteor/theme/dark.ts, packages/themes/src/meteor/theme/light.ts, packages/themes/src/pcte/theme/dark.tsx, packages/themes/src/pcte/theme/light.tsx, packages/types/package.json, packages/types/src/themeAugmentation.ts, packages/utils/package.json
🎫 https://resolvn.atlassian.net/browse/UXE-44
Created new `text.placeholder` color token
- Added to all themes
- Added to Palette/Foundation story
- Applied to `InputBase` for all themes and changed opacity to `1`
Fixed visual bugs in `Autocomplete`
- `endAdornment` vertical alignment
- Placeholder text's alignment with `InputLabel` when `multiple={true}`
- Checked all sizes across all themes
BEFORE:
AFTER:
=> [UXE-44] Add `text.placeholder` color token

packages/components/package.json, packages/components/src/DataGrid/hooks/useDataGridComponent.ts, packages/components/src/DataGrid/hooks/useGetScrollHeight.ts, packages/components/src/DataGrid/models/gridApi.ts, packages/themes/package.json, packages/types/package.json, packages/utils/package.json
Adds a function to apiRef that returns the scroll height of the virtual scroller.
=> feat(datagrid): add getScrollHeight to apiRef

packages/components/package.json, packages/components/src/Search/Search.tsx, packages/themes/package.json, packages/types/package.json, packages/utils/package.json
Use `display` property instead of `visibility` to hide clear button.
=> fix(Search): prevent clear button from cutting off placeholder text

packages/components/package.json, packages/storybook/src/DataGrid/DataGridVirtualization.stories.tsx, packages/themes/package.json, packages/themes/src/classic/components/DataGrid/themeOverrides.tsx, packages/themes/src/meteor/components/DataGrid/themeOverrides.tsx, packages/types/package.json, packages/utils/package.json
🎫 https://resolvn.atlassian.net/browse/UXE-152
Trade-off: The background color still gets cut off when shrinking down the right end of `DataGrid`'s body (first image). This is the default MUI behavior and only happens when `DataGrid`'s body has a horizontal scrollbar. It expands again after column resize (second image).
Striped rows get cut off if the content is wider than the container's width.
=> fix(DataGrid): expand striped row bgcolor

packages/themes/src/classic/components/Popover/themeOverrides.ts
Margin was applied to the `root` component, be it the container div that takes the whole screen, when it should've been applied to the `paper` component which is the actual menu container.
This change was tested with the [CFP-2116 Stacksim PR](https://github.com/Simspace/stack-optimization-web/pull/442). To do that you can:
1. run `yarn build-pack` on monorail
2. run `yarn link ~/absolute/path/to/monorail --all` from Stacksim 
3. (Optional) - if you run into dependency issues that cause linking error, like I did with clsx, you can temporarily match either one to avoid it
=> [CFP-2116] - Fixed menu alignment

packages/components/package.json, packages/themes/package.json, packages/themes/src/meteor/theme/dark.ts, packages/types/package.json, packages/utils/package.json
[CFP-2711](https://resolvn.atlassian.net/browse/CFP-2711)
This PR updates Meteor dark theme's design tokens.
- Raw colors
- Alias tokens
- Action tokens
[CFP-2711]: https://resolvn.atlassian.net/browse/CFP-2711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(Meteor): update dark theme palette

packages/components/package.json, packages/components/src/Button/Button.tsx, packages/storybook/src/Autocomplete/Autocomplete.stories.tsx, packages/storybook/src/Button/Button.stories.tsx, packages/storybook/src/Chip/Chip.stories.tsx, packages/storybook/src/Chip/ChipShowcase.stories.tsx, packages/storybook/src/List/List.stories.tsx, packages/storybook/src/Search/Search.stories.tsx, packages/storybook/src/Select/Select.stories.tsx, packages/storybook/src/TextField/TextField.stories.tsx, packages/storybook/src/helpers/helpers.ts, packages/storybook/src/helpers/storybook.ts, packages/storybook/src/theme/palette/Action.stories.tsx, packages/storybook/src/theme/palette/Foundation.stories.tsx, packages/storybook/src/theme/palette/Other.stories.tsx, packages/storybook/src/theme/palette/SemanticColors.stories.tsx, packages/storybook/src/theme/palette/palette.types.ts, packages/themes/package.json, packages/themes/src/meteor/components/Button/themeOverrides.ts, packages/themes/src/meteor/theme/baseTheme.ts, packages/themes/src/meteor/theme/dark.ts, packages/themes/src/meteor/theme/light.ts, packages/types/package.json, packages/utils/package.json
[CFP-2712](https://resolvn.atlassian.net/browse/CFP-2712) - Button theme updates
[CFP-2791](https://resolvn.atlassian.net/browse/CFP-2791) - Fix `secondary.contrastText` token reference
[Designs - Monorail/Button](https://www.figma.com/design/AF2iysvnM1NMDx7oCS93A3/%E2%9A%99%EF%B8%8F-Monorail?node-id=6543-37106&m=dev)
This PR updates the `Button` component's styles in the Meteor theme. 
It also includes a bug fix for secondary buttons light mode by updating `secondary.contrastText` from `RawColor.Orange700` to `RawColor.White`.
[CFP-2712]: https://resolvn.atlassian.net/browse/CFP-2712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CFP-2791]: https://resolvn.atlassian.net/browse/CFP-2791?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …
=> feat(Meteor): button theme updates

packages/components/package.json, packages/components/src/ButtonGroup/ButtonGroup.tsx, packages/components/src/SplitButton/SplitButton.tsx, packages/components/src/SplitButton/splitButtonProps.ts, packages/storybook/src/Button/Button.stories.tsx, packages/storybook/src/SplitButton/SplitButton.stories.tsx, packages/themes/package.json, packages/themes/src/meteor/components/SplitButton/themeOverrides.ts, packages/themes/src/meteor/theme/themeComponents.ts, packages/types/package.json, packages/utils/package.json
[CFP-2714](https://resolvn.atlassian.net/browse/CFP-2714)
[Designs](https://www.figma.com/file/AF2iysvnM1NMDx7oCS93A3/%E2%9A%99%EF%B8%8F-Monorail?type=design&node-id=6543%3A39713&mode=dev)
This PR introduces new override styling for the contained and outline variants of the meteor SplitButton component.
[CFP-2714]: https://resolvn.atlassian.net/browse/CFP-2714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CFP-2714] feat: update split button meteor styling

packages/themes/package.json, packages/themes/src/meteor/components/Autocomplete/themeOverrides.tsx, packages/themes/src/meteor/components/InputBase/themeOverrides.ts, packages/themes/src/meteor/components/InputLabel/themeOverrides.ts, packages/themes/src/meteor/components/OutlinedInput/themeOverrides.ts, packages/types/package.json, packages/utils/package.json
[Ticket](https://resolvn.atlassian.net/browse/CFP-2730)
[Design](https://www.figma.com/file/AF2iysvnM1NMDx7oCS93A3/%E2%9A%99%EF%B8%8F-Monorail?type=design&node-id=22449-40077&mode=design&t=a9rgHwjtvRSe7j5C-11)
This PR updates `themeOverride` colors for base input elements used in TextField, Select, Autocomplete, and Search components.
=> [CFP-2730] adds theme overrides to input components

packages/components/package.json, packages/components/src/ResizableDrawer/ResizableDrawer.tsx, packages/components/src/ResizeHandle/ResizeHandle.tsx, packages/storybook/src/Drawer/Drawer.stories.tsx, packages/themes/package.json, packages/types/package.json, packages/utils/package.json
[CFP-2850](https://resolvn.atlassian.net/browse/CFP-2850)
On resize, the `ResizableDrawer` shifts if an adjacent element is present. This PR includes a fix by subtracting the adjacent element's width from the drawer's updated width.
The resize handle's alignment was also updated so that it's always visible to the user.
https://github.com/Simspace/monorail/assets/35754959/50f18856-3a30-4822-a59d-7a612590f1d3
https://github.com/Simspace/monorail/assets/35754959/253cfcf9-4c45-4ddb-bafc-c19ae746947b
[CFP-2850]: https://resolvn.atlassian.net/browse/CFP-2850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(ResizableDrawer): subtract adjacent element's width when resizing

packages/themes/package.json, packages/themes/src/meteor/components/SplitButton/themeOverrides.ts
The MUI `ButtonGroup` component overlaps the buttons with a negative margin equal to the button border. Thus when hovering the left button took precedence over the right button overlapping its left border.
https://github.com/Simspace/monorail/assets/160646444/1bc325e3-221f-4111-9ba3-91fbe11d4c18
=> [PRTL-3923]: Fixed theme override for meteor split button

packages/components/package.json, packages/themes/package.json, packages/types/package.json, packages/utils/package.json
`@mui/x-tree-view` should be a peer-dependency only, since all other mui packages are peer dependencies. This is so that it doesn't install its own other versions of `@mui/system`, etc. in consuming projects.
=> chore: remove @mui/x-tree-view direct dependency

packages/components/package.json, packages/components/src/VirtualizedAutocomplete/VirtualizedAutocomplete.tsx, packages/themes/package.json, packages/types/package.json, packages/utils/package.json
Fixes a bug where a non-grouped `VirtualizedAutocomplete` would not render any items.
=> [No Ticket] fix: add totalCount to non-grouped virtualized autocomplete

packages/themes/src/meteor/components/Autocomplete/themeOverrides.tsx, packages/themes/src/meteor/components/Paper/themeOverrides.ts, packages/themes/src/meteor/theme/themeComponents.ts
https://resolvn.atlassian.net/browse/NG-480
Notion: [Dark Mode Updates (Elevations)](https://www.notion.so/simspace/Dark-Mode-Updates-3ada6d9a3ddd4d72b7fab780ec8f1a4d?pvs=4#08d6a7ad8cf149ce9ea217f9025461aa)
This PR overrides MUI's built-in `getOverlayAlpha` for the `Paper` component in Meteor dark mode.
=> [NG-480] feat: meteor paper overlay alpha values

packages/components/package.json, packages/components/src/PasswordTextField/PasswordTextField.tsx, packages/components/src/PasswordTextField/PasswordTextFieldProps.ts, packages/storybook/src/PasswordTextField/PasswordTextField.stories.tsx, packages/themes/package.json, packages/types/package.json, packages/utils/package.json
This PR enhances the PasswordTextField component to accept slots for the visibilityIcon and visibilityOffIcon.
=> feat: [NO-TICKET] enhance PasswordTextField to accept slots

packages/components/package.json, packages/components/src/FlexDrawer/FlexDrawer.tsx, packages/components/src/ResizeHandle/ResizeHandle.tsx, packages/storybook/src/Drawer/Drawer.stories.tsx, packages/themes/package.json, packages/types/package.json, packages/utils/package.json
https://resolvn.atlassian.net/browse/NG-2028
This PR fixes the `FlexDrawer` styles when the following props are used:
- `variant="temporary'`
- `resizable={true}`
- `anchor="right | top | bottom"`
Before
After
Before
After
Before
After
=> [NG-2028] fix: temporary FlexDrawer styles

packages/components/package.json, packages/components/src/DateTimePicker/DateTimePicker.tsx, packages/components/src/DesktopTimeDurationPicker/DesktopTimeDurationPicker.tsx, packages/components/src/DesktopTimePicker/DesktopTimePicker.tsx, packages/storybook/src/DesktopTimeDurationPicker/DesktopTimeDurationPicker.stories.tsx, packages/themes/package.json, packages/themes/src/classic/components/PickersLayout/themeOverrides.ts, packages/types/package.json, packages/utils/package.json
[Ticket](https://resolvn.atlassian.net/browse/PRTL-4583)
- Removed padding from `themeOverride` object for `MonorailPickersLayoutOverrides` since it affects both DateTimePicker and DesktopTimePicker and it's different for each.
- Added paddings to DateTimePicker and DesktopTimePicker
- Force border bottom to be hidden for timer container
=> [PRTL-4583] feat: Time picker

packages/components/package.json, packages/components/src/DialogHeader/DialogHeader.tsx, packages/components/src/DialogHeader/dialogHeaderProps.ts, packages/themes/package.json, packages/types/package.json, packages/utils/package.json
This PR fixes `DialogHeader`'s text overflow bug.
With `slotProps.typography.lineClamp`
=> [NO-TICKET] fix(DialogHeader): wrap text when title is too long

packages/components/package.json, packages/themes/package.json, packages/themes/src/meteor/components/PaginationItem/themeOverrides.ts, packages/types/package.json, packages/utils/package.json
Jira: https://resolvn.atlassian.net/browse/NG-2131
This fixes the red hover color on a pagination item
before:
after:
=> [NG-2131] Fix PaginationItem colors

packages/components/package.json, packages/components/src/FileUpload/FileUpload.tsx, packages/components/src/FileUpload/fileUploadProps.ts, packages/storybook/src/FileUpload/FileUpload.stories.tsx, packages/themes/package.json, packages/types/package.json
These are breaking changes as now `UploadFile` returns a `ReadonlyArray<File>`.
=> [PRTL-4871] Adapt UploadFile component to accept multiple files
